import { StarNumber, StarRatingKeywords } from '@/types/starRating';

export const DefaultStarRatingSet = {
	userRating: {
		keywordsByStar: {
			1: [
				'Phase I',
				'Phase 1',
				'Grants',
				'Any Large',
				'Investors',
				'Accepted',
				'New',
				'Signs',
				'Merger',
				'Gain',
				'Win',
				'Accept',
				'Accepts',
				'Secures',
				'Signed',
				'Sign',
				'Acquisition',
				'Merge',
				'Gains',
				'Patent',
			],
			2: [
				'Phase II',
				'Phase 2',
				'Receives',
				'FDA',
				'Approval',
				'Benefit',
				'Benefits',
				'Beneficial',
				'Fast Track',
				'Breakout',
				'Acquirements',
				'Expand',
				'Expansion',
				'Contract',
				'Completes',
				'Promising',
				'Achieve',
				'Achieves',
				'Achievement',
				'Achievements',
				'Receive',
				'Received',
				'Approves',
				'Approve',
				'Approved',
				'Breakouts',
				'Contracts',
				'Complete',
				'Completed',
				'Achieved',
				'Launches',
				'Purchase',
				'Repurchase',
				'Bankruptcy',
				'Special',
			],
			3: [
				'Phase III',
				'Phase 3',
				'Positive',
				'Top-Line',
				'Significant',
				'Demonstrates',
				'Treatment',
				'Drug Trial',
				'Drug Trials',
				'Agreement',
				'Cancer',
				'Partnership',
				'Collaboration',
				'Improvement',
				'Improvements',
				'Successful',
				'Billionaire',
				'Carl Icahn',
				'Increase',
				'Awarded',
				'Top of the Line',
				'Demonstrate',
				'Demonstrated',
				'Demonstrating',
				'Demonstration',
				'Significance',
				'Significantly',
				'Agreements',
				'Partnerships',
				'Collab',
				'Collaborations',
				'Success',
				'Billion',
				'Awards',
				'Award',
				'Important',
				'Survival',
				'Reached',
				'Goal',
			],
			4: [
				'Positive endpoint',
				'Endpoints',
				'Endpoint',
				'Primary',
				'Positive CEO statement',
			],
		},
	},
};

export const initialStarRating: StarRatingKeywords = {
	1: [],
	2: [],
	3: [],
	4: [],
};
